Vagrant.configure(2) do |config|
  config.vm.box = "bento/debian-12"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define "alagmiriS" do |server|
    server.vm.hostname = "alagmiriS"
    server.vm.network "private_network",ip: "192.168.56.110"
    server.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -qq 
      sudo apt-get install -qq -y curl net-tools
      echo 'export PATH=$PATH:/sbin' >> /home/vagrant/.bashrc
      source /home/vagrant/.bashrc

      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-ip 192.168.56.110" \
        K3S_TOKEN="#{ENV['K3S_TOKEN']}" \
        K3S_KUBECONFIG_MODE="644" sh -s -
        kubectl apply -f /vagrant/confs/namespace.yaml
        sleep 10
  
      kubectl apply -f /vagrant/confs/app1.yaml
      kubectl apply -f /vagrant/confs/app2.yaml
      kubectl apply -f /vagrant/confs/app3.yaml
      kubectl apply -f /vagrant/confs/ingress.yaml
    SHELL
  end
end