Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"

  TEAM_LOGIN = "alagmiri" 

  config.vm.define "#{TEAM_LOGIN}S" do |server|
    server.vm.hostname = "#{TEAM_LOGIN}S"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end

    server.vm.provision "shell", inline: <<-SHELL
      set -eux
      apt-get update -y
      apt-get install -y curl ca-certificates

      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server \
        --node-ip=192.168.56.110 \
        --advertise-address=192.168.56.110 \
        --tls-san=192.168.56.110 \
        --disable traefik \
        --disable servicelb \
        --disable metrics-server" sh -

      ln -sf /usr/local/bin/k3s /usr/local/bin/kubectl

      mkdir -p /home/vagrant/.kube
      cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
      chown -R vagrant:vagrant /home/vagrant/.kube
      sed -i 's/127.0.0.1/192.168.56.110/g' /home/vagrant/.kube/config
      chmod 600 /home/vagrant/.kube/config

      cat /var/lib/rancher/k3s/server/node-token > /vagrant/node-token
      chmod 0644 /vagrant/node-token

      cp /etc/rancher/k3s/k3s.yaml /vagrant/k3s.yaml
      sed -i 's/127.0.0.1/192.168.56.110/g' /vagrant/k3s.yaml
      chmod 0644 /vagrant/k3s.yaml

      echo 'export KUBECONFIG=/home/vagrant/.kube/config' >> /home/vagrant/.bashrc
      echo 'export KUBECONFIG=/home/vagrant/.kube/config' >> /home/vagrant/.profile

      mkdir -p /root/.kube
      cp /home/vagrant/.kube/config /root/.kube/config
      chmod 600 /root/.kube/config
    SHELL
  end

  # =========================
  # ServerWorker (Agent)
  # =========================
  config.vm.define "#{TEAM_LOGIN}SW" do |worker|
    worker.vm.hostname = "#{TEAM_LOGIN}SW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end

    worker.vm.provision "shell", inline: <<-SHELL
      set -eux
      apt-get update -y
      apt-get install -y curl ca-certificates

      while [ ! -s /vagrant/node-token ]; do
        sleep 2
      done
      while [ ! -s /vagrant/k3s.yaml ]; do
        sleep 2
      done

      TOKEN=$(cat /vagrant/node-token)

      until curl -k https://192.168.56.110:6443/healthz >/dev/null 2>&1; do
        sleep 2
      done

      curl -sfL https://get.k3s.io | K3S_URL="https://192.168.56.110:6443" K3S_TOKEN="$TOKEN" \
        INSTALL_K3S_EXEC="agent --node-ip=192.168.56.111" sh -

      ln -sf /usr/local/bin/k3s /usr/local/bin/kubectl

      mkdir -p /home/vagrant/.kube
      cp /vagrant/k3s.yaml /home/vagrant/.kube/config
      chown -R vagrant:vagrant /home/vagrant/.kube
      chmod 600 /home/vagrant/.kube/config
sudo rm -rf /tmp/*
sudo rm -rf /var/tmp/*
sudo apt-get clean
sudo apt-get autoclean
      echo 'export KUBECONFIG=/home/vagrant/.kube/config' >> /home/vagrant/.bashrc
      echo 'export KUBECONFIG=/home/vagrant/.kube/config' >> /home/vagrant/.profile


      mkdir -p /root/.kube
      cp /home/vagrant/.kube/config /root/.kube/config
      chmod 600 /root/.kube/config
    SHELL
  end
end